# Generated by Django 2.2.6 on 2019-10-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predios',
            name='num_Matr_Inmob',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
