# Generated by Django 2.2.6 on 2019-10-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Predio', models.CharField(max_length=200)),
                ('num_Matr_Inmob', models.CharField(max_length=200)),
                ('Tipo', models.CharField(max_length=200)),
                ('ced_Catastral', models.CharField(max_length=200)),
                ('dir_Predio', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'predio',
                'verbose_name_plural': 'predios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Prop', models.CharField(max_length=200)),
                ('ced_Prop', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Predios')),
                ('propietarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Propietarios')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-created'],
            },
        ),
    ]
