# Generated by Django 2.2.6 on 2019-10-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Predios'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='propietarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietarios.Propietarios'),
        ),
        migrations.DeleteModel(
            name='Predios',
        ),
        migrations.DeleteModel(
            name='Propietarios',
        ),
    ]
