# Generated by Django 2.2.6 on 2019-10-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietarios',
            name='ced_Prop',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
